version: '3'

services:
  app:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    command: npm run dev
    volumes:
      - ../../:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - redis

  worker:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    command: npm run dev:worker
    volumes:
      - ../../:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - app
      - redis

  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
