version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    entrypoint: ./docker-entrypoint.sh
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - postgres

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev:worker
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - app

  redis:
    image: "redis:alpine"
    restart: always
    command: redis-server
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  redis_data:
  postgres:
